try{thing();}catch(err){console.error(err);}finally{console.log("done");};